notifications:
  email: false

language: python

env:
  - TOX_ENV=beets_master COVERAGE=1
  - TOX_ENV=beets_1.4.1
  - TOX_ENV=flake8

install:
  - "pip install tox"
  - "[ ! -z $COVERAGE ] && pip install coveralls || true"

script: "tox -e $TOX_ENV"

after_success:
  - "[ ! -z $COVERAGE ] && coveralls || true"
