notifications:
  email:
    recipients:
      - secure: SCVrl5324WVy0WDH1480D0Yxs/iP7n74QCnBunfWBhXsvaQmL4M06+6ICuw1yZx1hwU+qSRcGWXO8ryPu3Z3mnW+VZ6bfRAeACDiHpbXkb+4q6q86EpzvIgAy9gg3QvUXsLZUXfSN0KNdgbI+lBMiG9R9Mc7XtMizsinL6eohpU=  # wisp3rwind
    on_success: never
    on_failure: change

language: python

matrix:
  include:
    - env: TOX_ENV=py27-beets_master
      python: 2.7
    - env: TOX_ENV=py27-beets_release
      python: 2.7

    - env: TOX_ENV=py36-beets_master
      python: 3.6
    - env: TOX_ENV=py36-beets_release
      python: 3.6

      # xenial is required to run Python >= 3.7, cf.
      # https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-402045581
    - env: TOX_ENV=py38-beets_master COVERAGE=1
      python: 3.8
      dist: xenial
    - env: TOX_ENV=py38-beets_release
      python: 3.8
      dist: xenial

    - env: TOX_ENV=py39-beets_master
      python: 3.9-dev
      dist: xenial
      sudo: yes
    - env: TOX_ENV=py39-beets_release
      python: 3.9-dev
      dist: xenial
      sudo: yes

    - env: TOX_ENV=py38-flake8
      python: 3.8

install:
  - "pip install tox"
  - "[ ! -z $COVERAGE ] && pip install coveralls || true"

script: "tox -e $TOX_ENV"

after_success:
  - "[ ! -z $COVERAGE ] && coveralls || true"
